<a href="https://colab.research.google.com/github/vedashreebhalerao/fp/blob/main/data_preprosessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [7]:
import pandas as pd
import numpy as np

In [11]:
df=pd.read_csv('/content/drive/MyDrive/DMVL sem 6/Iris_data_sample.csv')

In [12]:
df.head(5)

Unnamed: 0 SepalLengthCm  SepalWidthCm PetalLengthCm  PetalWidthCm  \
0           1           5.1           3.5           1.4           0.2   
1           2           4.9           NaN           1.4           0.2   
2           3           4.7           3.2           1.3           0.2   
3           4            ??           3.1           1.5           0.2   
4           5             5           3.6           ###           0.2   

       Species  
0  Iris-setosa  
1          NaN  
2  Iris-setosa  
3  Iris-setosa  
4  Iris-setosa

In [13]:
df.tail(10)

Unnamed: 0 SepalLengthCm  SepalWidthCm PetalLengthCm  PetalWidthCm  \
140         141           6.7           3.1           5.6           2.4   
141         142           6.9           3.1           5.1           2.3   
142         143           5.8           2.7           5.1           1.9   
143         144           6.8           3.2           5.9           2.3   
144         145           6.7           3.3           5.7           2.5   
145         146           6.7           3.0           5.2           2.3   
146         147           6.3           2.5             5           1.9   
147         148           6.5           3.0           5.2           2.0   
148         149           6.2           3.4           5.4           2.3   
149         150           5.9           3.0           5.1           1.8   

            Species  
140  Iris-virginica  
141  Iris-virginica  
142  Iris-virginica  
143  Iris-virginica  
144  Iris-virginica  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [14]:
df=pd.read_csv('/content/drive/MyDrive/DMVL sem 6/Iris_data_sample.csv',index_col=0)

In [15]:
df

SepalLengthCm  SepalWidthCm PetalLengthCm  PetalWidthCm         Species
1             5.1           3.5           1.4           0.2     Iris-setosa
2             4.9           NaN           1.4           0.2             NaN
3             4.7           3.2           1.3           0.2     Iris-setosa
4              ??           3.1           1.5           0.2     Iris-setosa
5               5           3.6           ###           0.2     Iris-setosa
..            ...           ...           ...           ...             ...
146           6.7           3.0           5.2           2.3  Iris-virginica
147           6.3           2.5             5           1.9  Iris-virginica
148           6.5           3.0           5.2           2.0  Iris-virginica
149           6.2           3.4           5.4           2.3  Iris-virginica
150           5.9           3.0           5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [17]:
print(df.dtypes)

SepalLengthCm     object
SepalWidthCm     float64
PetalLengthCm     object
PetalWidthCm     float64
Species           object
dtype: object


In [18]:
df.describe()

SepalWidthCm  PetalWidthCm
count    149.000000    150.000000
mean       3.054362      1.198667
std        0.435034      0.763161
min        2.000000      0.100000
25%        2.800000      0.300000
50%        3.000000      1.300000
75%        3.300000      1.800000
max        4.400000      2.500000

In [19]:
df.describe(include='all')

SepalLengthCm  SepalWidthCm PetalLengthCm  PetalWidthCm  \
count            150    149.000000           149    150.000000   
unique            36           NaN            44           NaN   
top                5           NaN           1.5           NaN   
freq              10           NaN            14           NaN   
mean             NaN      3.054362           NaN      1.198667   
std              NaN      0.435034           NaN      0.763161   
min              NaN      2.000000           NaN      0.100000   
25%              NaN      2.800000           NaN      0.300000   
50%              NaN      3.000000           NaN      1.300000   
75%              NaN      3.300000           NaN      1.800000   
max              NaN      4.400000           NaN      2.500000   

                Species  
count               149  
unique                3  
top     Iris-versicolor  
freq                 50  
mean                NaN  
std                 NaN  
min                 NaN  
25%                 NaN  
50%                 NaN  
75%                 NaN  
max                 NaN

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, 1 to 150
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   SepalLengthCm  150 non-null    object 
 1   SepalWidthCm   149 non-null    float64
 2   PetalLengthCm  149 non-null    object 
 3   PetalWidthCm   150 non-null    float64
 4   Species        149 non-null    object 
dtypes: float64(2), object(3)
memory usage: 7.0+ KB


In [24]:
df1=df.copy(deep=True)


In [25]:
df1.index

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       141, 142, 143, 144, 145, 146, 147, 148, 149, 150],
      dtype='int64', length=150)

In [28]:
df1.columns

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [29]:
df1.loc[:,'SepalLengthCm']

1      5.1
2      4.9
3      4.7
4       ??
5        5
      ... 
146    6.7
147    6.3
148    6.5
149    6.2
150    5.9
Name: SepalLengthCm, Length: 150, dtype: object

In [30]:
df1.iloc[:,1]

1      3.5
2      NaN
3      3.2
4      3.1
5      3.6
      ... 
146    3.0
147    2.5
148    3.0
149    3.4
150    3.0
Name: SepalWidthCm, Length: 150, dtype: float64

In [31]:
df1.iloc[0:5,]

SepalLengthCm  SepalWidthCm PetalLengthCm  PetalWidthCm      Species
1           5.1           3.5           1.4           0.2  Iris-setosa
2           4.9           NaN           1.4           0.2          NaN
3           4.7           3.2           1.3           0.2  Iris-setosa
4            ??           3.1           1.5           0.2  Iris-setosa
5             5           3.6           ###           0.2  Iris-setosa

In [32]:
df1.iloc[0:3,]

SepalLengthCm  SepalWidthCm PetalLengthCm  PetalWidthCm      Species
1           5.1           3.5           1.4           0.2  Iris-setosa
2           4.9           NaN           1.4           0.2          NaN
3           4.7           3.2           1.3           0.2  Iris-setosa

In [33]:
df1.iloc[0:5,0:2]

SepalLengthCm  SepalWidthCm
1           5.1           3.5
2           4.9           NaN
3           4.7           3.2
4            ??           3.1
5             5           3.6

In [34]:
df1.dtypes.value_counts()

object     3
float64    2
Name: count, dtype: int64

In [37]:
np.unique(df['SepalLengthCm'])

array(['4.3', '4.4', '4.5', '4.6', '4.7', '4.8', '4.9', '5', '5.1', '5.2',
       '5.3', '5.4', '5.5', '5.6', '5.7', '5.8', '5.9', '6', '6.1', '6.2',
       '6.3', '6.4', '6.5', '6.6', '6.7', '6.8', '6.9', '7', '7.1', '7.2',
       '7.3', '7.4', '7.6', '7.7', '7.9', '??'], dtype=object)

In [40]:
np.unique(df['PetalWidthCm'])

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6,
       1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5])

In [41]:
np.unique(df['SepalLengthCm'])

array(['4.3', '4.4', '4.5', '4.6', '4.7', '4.8', '4.9', '5', '5.1', '5.2',
       '5.3', '5.4', '5.5', '5.6', '5.7', '5.8', '5.9', '6', '6.1', '6.2',
       '6.3', '6.4', '6.5', '6.6', '6.7', '6.8', '6.9', '7', '7.1', '7.2',
       '7.3', '7.4', '7.6', '7.7', '7.9', '??'], dtype=object)

In [42]:
df1.PetalLengthCm.unique()

array(['1.4', '1.3', '1.5', '###', nan, '1.6', '1.1', '1.2', '1.7', '1',
       '1.9', '4.7', '4.5', '4.9', '4', '4.6', '3.3', '3.9', '3.5', '4.2',
       '3.6', '4.4', '4.1', '4.8', '4.3', '5', '3.8', '3.7', '5.1', '3',
       '6', '5.9', '5.6', '5.8', '6.6', '6.3', '6.1', '5.3', '5.5', '6.7',
       '6.9', '5.7', '6.4', '5.4', '5.2'], dtype=object)

In [44]:
df1.Species.unique()

array(['Iris-setosa', nan, 'Iris-versicolor', 'Iris-virginica'],
      dtype=object)

In [47]:
df1.SepalWidthCm.unique()

array([3.5, nan, 3.2, 3.1, 3.6, 3.9, 3.4, 2.9, 3.7, 3. , 4. , 4.4, 3.8,
       3.3, 4.1, 4.2, 2.3, 2.8, 2.4, 2.7, 2. , 2.2, 2.5, 2.6])

In [48]:
iris_df=pd.read_csv('/content/drive/MyDrive/DMVL sem 6/Iris_data_sample.csv',index_col=0, na_values=['NA'])

In [61]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X= iris_df.iloc[:,0:-1]
y=iris_df.iloc[:,4]

In [65]:
import numpy as np
from sklearn.impute import SimpleImputer


iris_df.replace(['??', '###'], np.nan, inplace=True)


imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X = iris_df.iloc[:, 0:-1]
y = iris_df.iloc[:, 4]
imputer = imputer.fit(X)


X = imputer.transform(X)


In [66]:
imputer = imputer.fit(X)
X = imputer.transform(X)
X

array([[5.1       , 3.5       , 1.4       , 0.2       ],
       [4.9       , 3.05436242, 1.4       , 0.2       ],
       [4.7       , 3.2       , 1.3       , 0.2       ],
       [5.85167785, 3.1       , 1.5       , 0.2       ],
       [5.        , 3.6       , 3.78851351, 0.2       ],
       [5.4       , 3.9       , 3.78851351, 0.4       ],
       [4.6       , 3.4       , 1.4       , 0.3       ],
       [5.        , 3.4       , 1.5       , 0.2       ],
       [4.4       , 2.9       , 1.4       , 0.2       ],
       [4.9       , 3.1       , 1.5       , 0.1       ],
       [5.4       , 3.7       , 1.5       , 0.2       ],
       [4.8       , 3.4       , 1.6       , 0.2       ],
       [4.8       , 3.        , 1.4       , 0.1       ],
       [4.3       , 3.        , 1.1       , 0.1       ],
       [5.8       , 4.        , 1.2       , 0.2       ],
       [5.7       , 4.4       , 1.5       , 0.4       ],
       [5.4       , 3.9       , 1.3       , 0.4       ],
       [5.1       , 3.5       ,