<a href="https://colab.research.google.com/github/vedashreebhalerao/fp/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing
from google.colab import drive

In [7]:
drive.mount('/content/gdrive/')

Mounted at /content/gdrive/


In [9]:
df = pd.read_csv('/content/gdrive/MyDrive/DMVL sem 6/ChurnData.csv')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 28 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   tenure    200 non-null    float64
 1   age       200 non-null    float64
 2   address   200 non-null    float64
 3   income    200 non-null    float64
 4   ed        200 non-null    float64
 5   employ    200 non-null    float64
 6   equip     200 non-null    float64
 7   callcard  200 non-null    float64
 8   wireless  200 non-null    float64
 9   longmon   200 non-null    float64
 10  tollmon   200 non-null    float64
 11  equipmon  200 non-null    float64
 12  cardmon   200 non-null    float64
 13  wiremon   200 non-null    float64
 14  longten   200 non-null    float64
 15  tollten   200 non-null    float64
 16  cardten   200 non-null    float64
 17  voice     200 non-null    float64
 18  pager     200 non-null    float64
 19  internet  200 non-null    float64
 20  callwait  200 non-null    float6

In [11]:
df.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  

[5 rows x 28 columns]

In [12]:
df.describe()

tenure         age     address       income         ed     employ  \
count  200.000000  200.000000  200.000000   200.000000  200.00000  200.00000   
mean    35.505000   41.165000   11.650000    75.130000    2.82500   10.22500   
std     21.640971   13.076803   10.158419   128.430468    1.28555    8.95743   
min      1.000000   19.000000    0.000000     9.000000    1.00000    0.00000   
25%     16.750000   31.000000    3.000000    31.000000    2.00000    3.00000   
50%     33.500000   40.000000    9.000000    48.000000    3.00000    7.50000   
75%     55.250000   51.000000   18.000000    80.000000    4.00000   17.00000   
max     72.000000   76.000000   48.000000  1668.000000    5.00000   44.00000   

            equip    callcard    wireless    longmon  ...       pager  \
count  200.000000  200.000000  200.000000  200.00000  ...  200.000000   
mean     0.425000    0.705000    0.290000   11.78925  ...    0.275000   
std      0.495584    0.457187    0.454901    9.88725  ...    0.447635   
min      0.000000    0.000000    0.000000    1.10000  ...    0.000000   
25%      0.000000    0.000000    0.000000    5.53750  ...    0.000000   
50%      0.000000    1.000000    0.000000    8.25000  ...    0.000000   
75%      1.000000    1.000000    1.000000   14.30000  ...    1.000000   
max      1.000000    1.000000    1.000000   62.30000  ...    1.000000   

         internet   callwait      confer       ebill     loglong     logtoll  \
count  200.000000  200.00000  200.000000  200.000000  200.000000  200.000000   
mean     0.440000    0.45500    0.460000    0.440000    2.193285    3.229185   
std      0.497633    0.49922    0.499648    0.497633    0.731282    0.281019   
min      0.000000    0.00000    0.000000    0.000000    0.095000    1.749000   
25%      0.000000    0.00000    0.000000    0.000000    1.711750    3.226500   
50%      0.000000    0.00000    0.000000    0.000000    2.110000    3.240000   
75%      1.000000    1.00000    1.000000    1.000000    2.660000    3.240000   
max      1.000000    1.00000    1.000000    1.000000    4.132000    4.227000   

            lninc     custcat       churn  
count  200.000000  200.000000  200.000000  
mean     3.951015    2.475000    0.290000  
std      0.752553    1.079445    0.454901  
min      2.197000    1.000000    0.000000  
25%      3.434000    2.000000    0.000000  
50%      3.871000    2.000000    0.000000  
75%      4.382000    3.000000    1.000000  
max      7.419000    4.000000    1.000000  

[8 rows x 28 columns]

In [13]:
df.columns

Index(['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',
       'callcard', 'wireless', 'longmon', 'tollmon', 'equipmon', 'cardmon',
       'wiremon', 'longten', 'tollten', 'cardten', 'voice', 'pager',
       'internet', 'callwait', 'confer', 'ebill', 'loglong', 'logtoll',
       'lninc', 'custcat', 'churn'],
      dtype='object')

In [14]:
df = df[['tenure' , 'age' , 'address' , 'income' , 'ed' , 'employ' , 'equip' , 'callcard' , 'wireless' , 'churn']]
df['churn'] = df['churn'].astype('int')
df.head()

<ipython-input-14-439dfaf53416>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['churn'] = df['churn'].astype('int')


tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   churn  
0      1  
1      1  
2      0  
3      0  
4      0

In [15]:
X = np.asarray(df[['tenure' , 'age' , 'address' , 'income' , 'ed' , 'employ' , 'equip' , 'callcard' , 'wireless' , 'churn']])
X[0:5]

array([[ 11.,  33.,   7., 136.,   5.,   5.,   0.,   1.,   1.,   1.],
       [ 33.,  33.,  12.,  33.,   2.,   0.,   0.,   0.,   0.,   1.],
       [ 23.,  30.,   9.,  30.,   1.,   2.,   0.,   0.,   0.,   0.],
       [ 38.,  35.,   5.,  76.,   2.,  10.,   1.,   1.,   1.,   0.],
       [  7.,  35.,  14.,  80.,   2.,  15.,   0.,   1.,   0.,   0.]])

In [16]:
y = np.asarray(df['churn'])
y[0:5]

array([1, 1, 0, 0, 0])

In [17]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)
X[0:5]

array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ,  1.6961288 ,
        -0.58477841, -0.85972695,  0.64686916,  1.56469673,  1.56469673],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061, -0.6433592 ,
        -1.14437497, -0.85972695, -1.54590766, -0.63910148,  1.56469673],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817, -1.42318853,
        -0.92053635, -0.85972695, -1.54590766, -0.63910148, -0.63910148],
       [ 0.11557989, -0.47262854, -0.65627219,  0.00679109, -0.6433592 ,
        -0.02518185,  1.16316   ,  0.64686916,  1.56469673, -0.63910148],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451, -0.6433592 ,
         0.53441472, -0.85972695,  0.64686916, -0.63910148, -0.63910148]])

In [18]:
from sklearn.model_selection import train_test_split
Xtrain , Xtest , ytrain , ytest = train_test_split(X , y , test_size = 0.2 , random_state = 4)
print("Training Set : " , Xtrain.shape , ytrain.shape)
print("Testing Set : " , Xtest.shape , ytest.shape)

Training Set :  (160, 10) (160,)
Testing Set :  (40, 10) (40,)


In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C = 0.01 , solver = 'liblinear').fit(Xtrain , ytrain)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [ ]:
yhat = LR.predict(Xtest)
yhat

array([0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

In [20]:
yhat_prob = LR.predict_proba(Xtest)
yhat_prob

array([[0.65136938, 0.34863062],
       [0.63472151, 0.36527849],
       [0.35967279, 0.64032721],
       [0.7093506 , 0.2906494 ],
       [0.36226353, 0.63773647],
       [0.40753603, 0.59246397],
       [0.33785482, 0.66214518],
       [0.63426687, 0.36573313],
       [0.27108557, 0.72891443],
       [0.40510656, 0.59489344],
       [0.62243817, 0.37756183],
       [0.65272591, 0.34727409],
       [0.60451524, 0.39548476],
       [0.28008563, 0.71991437],
       [0.72607113, 0.27392887],
       [0.59839578, 0.40160422],
       [0.33624228, 0.66375772],
       [0.30890535, 0.69109465],
       [0.31706636, 0.68293364],
       [0.38916266, 0.61083734],
       [0.59265337, 0.40734663],
       [0.58456293, 0.41543707],
       [0.71009115, 0.28990885],
       [0.58412042, 0.41587958],
       [0.56777919, 0.43222081],
       [0.75575842, 0.24424158],
       [0.55055553, 0.44944447],
       [0.57958783, 0.42041217],
       [0.58183136, 0.41816864],
       [0.75966601, 0.24033399],
       [0.